In [79]:
import numpy as np
import pandas as pd

In [80]:
dataset = pd.read_csv('metroRailData.csv')

In [103]:
dataset

Name  Salary OwnPrivateCar  Age      Area usedMetroRail
0  Anindya   25000            No   25  Khilgaon           Yes
1    Zaman   40000           Yes   37   Pallabi           Yes
2  Kowshic   36000            No   24    Lalbag            No
3   Arafat   26000           Yes   25    Uttara           Yes
4   Surovi   15000            No   22  Khilgaon            No

In [82]:
feature_name = ['Salary', 'OwnPrivateCar', 'Age']
label = 'usedMetroRail'

X = dataset[feature_name]
y = dataset[label]

In [83]:
X

Salary OwnPrivateCar  Age
0   25000            No   25
1   40000           Yes   37
2   36000            No   24
3   26000           Yes   25
4   15000            No   22

In [84]:
y

0    Yes
1    Yes
2     No
3    Yes
4     No
Name: usedMetroRail, dtype: object

In [85]:
from sklearn.preprocessing import LabelEncoder

labelEncoder_X = LabelEncoder()
X.iloc[:, 1] = labelEncoder_X.fit_transform(X.iloc[:, 1])

y = labelEncoder_X.fit_transform(y)


In [86]:
y

array([1, 1, 0, 1, 0])

In [87]:
y

array([1, 1, 0, 1, 0])

In [88]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [89]:
y

array([1, 1, 0, 1, 0])

In [90]:
X_train['Salary'] = X_train['Salary'].astype(int)
X_train['Age'] = X_train['Age'].astype(int)

In [91]:
X_train

Salary OwnPrivateCar  Age
4   15000             0   22
2   36000             0   24
0   25000             0   25
3   26000             1   25

In [92]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()

model.fit(X_train, y_train)

DecisionTreeClassifier()

In [93]:
y_hat = model.predict(X_test)

In [95]:
y_test, y_hat

(array([1]), array([1]))

In [105]:
X_test

Salary OwnPrivateCar  Age
1   40000             1   37

In [106]:
xx =[20000, 0, 12]

model.predict([xx])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0])